---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=${SUID}
      - PGID=${SGID}
      - TZ=Europe/Zurich
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ./appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
