---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Zurich
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ${OSPARC_APPDATA_CONFIG_VOLUME}:/config
      - ${OSPARC_APPDATA_INPUTS_VOLUME}:${INPUT_FOLDER}:ro
      - ${OSPARC_APPDATA_OUTPUTS_VOLUME}:${OUTPUT_FOLDER}
    ports:
      - 8443:8443
    entrypoint: ["ln", "-s", "/config/.osparc/exchange", "/config/.osparc/workflow"]

    restart: unless-stopped
